# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91abbd2ee394bc984421dc94b77e018edbeb587fdddceaa1c4f9d62c3e69fe2879c5a6d23d2662304f1c88527545a0d85e67f6aae25f2b4b77d1adb9718565ef

test:
  secret_key_base: 06bc0f83c8604bbe4887d444964c866c53e5382d115e1bc31fc7aa5152966024702a5850f9bb0f81551938a8756273419b68b22df7ab4d4347645a051c0722bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
